#!/bin/sh

folder_app="/Applications/iSABnzbd.app/"
folder_data="/var/mobile/Documents/JypyzProducts/iSABnzbd/"
echo
echo Data folder: $folder_data
echo
echo Adjusting permissions...

chown -R root:wheel $folder_app
chmod 755 $folder_app
chown -R mobile:mobile $folder_data
chmod 775 $folder_data
chmod +x $folder_app/*.py
chmod +x $folder_app/start.sh
chmod +x $folder_app/tools/*.py

echo

echo Enable multi-language support...
cd $folder_app
python tools/make_mo.py

echo
echo Done!
